In [1]:
import pandas as pd
import numpy as np

In [8]:
week_att_df = pd.read_csv('Resources\Class Attendance 11043 - 6-20-2022 - 6-24-2022.csv', nrows=1165)
week_att_df

,Textbox258,Textbox345,DivisionDisplay,DistrictDisplay,Textbox331,Textbox332,Textbox67,TotalForClass2,Textbox33,Completed2,...,Textbox28,Textbox29,Textbox30,Textbox23,Textbox13,Textbox44,UserDisplay,BookingStatus1,SpecialCredit,Textbox329
0,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,22,20,2,0,0,Heather Adams (75524705) [F],Completed Booking,NaN,hjhadams@gmail.com
1,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,22,20,2,0,0,Emily Adams (87506651) [F],Completed Booking,NaN,hjhadams1977@gmail.com
2,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,22,20,2,0,0,Elyse Adams (87585364) [Other],Completed Booking,NaN,elyseadams2008@gmail.com
3,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,22,20,2,0,0,Chris Carr (75524549) [M],Cancelled Outside Policy Rules - Session Lost,NaN,chrisgcarr@gmail.com
4,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,22,20,2,0,0,Susie Cook (88007991) [Other],Completed Booking,NaN,susie.cook@compass.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,29,18,11,0,0,Dave Sagraves (75524526) [M],Completed Booking,NaN,dave@sagraves.com
1161,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,29,18,11,0,0,Shelene Walker (75524597) [F],Completed Booking,NaN,mikeandshelene@hotmail.com
1162,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,29,18,11,0,0,Michael Ward (84454920) [M],Cancelled Outside Policy Rules - Session Lost,NaN,michaelward1@bellsouth.net
1163,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,29,18,11,0,0,Patrick Whitlock (75524489) [M],Completed Booking,NaN,pwhitloc@gmail.com
1164,Class Attendance - Iron Tribe - Franklin (1104...,3 Classes - 4 Instructors - 242 Members,Division: Warren (2266),District: TN (5771),59,98.7 %,48.0 %,"1,180","1,165",566,...,20,29,18,11,0,0,Matt Wood (75524649) [M],Cancelled Within Policy Rules - No session cre...,NaN,matthew.d.wood85@gmail.com

In [17]:
week_att_df.drop(['Textbox258','Textbox345','DivisionDisplay','DistrictDisplay','SpecialCredit'], axis=1)

,Textbox331,Textbox332,Textbox67,TotalForClass2,Textbox33,Completed2,Textbox19,Textbox9,NoShow2,Textbox306,...,Textbox349,Textbox28,Textbox29,Textbox30,Textbox23,Textbox13,Textbox44,UserDisplay,BookingStatus1,Textbox329
0,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,100.0 %,20,22,20,2,0,0,Heather Adams (75524705) [F],Completed Booking,hjhadams@gmail.com
1,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,100.0 %,20,22,20,2,0,0,Emily Adams (87506651) [F],Completed Booking,hjhadams1977@gmail.com
2,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,100.0 %,20,22,20,2,0,0,Elyse Adams (87585364) [Other],Completed Booking,elyseadams2008@gmail.com
3,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,100.0 %,20,22,20,2,0,0,Chris Carr (75524549) [M],Cancelled Outside Policy Rules - Session Lost,chrisgcarr@gmail.com
4,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,100.0 %,20,22,20,2,0,0,Susie Cook (88007991) [Other],Completed Booking,susie.cook@compass.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1160,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,90.0 %,20,29,18,11,0,0,Dave Sagraves (75524526) [M],Completed Booking,dave@sagraves.com
1161,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,90.0 %,20,29,18,11,0,0,Shelene Walker (75524597) [F],Completed Booking,mikeandshelene@hotmail.com
1162,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,90.0 %,20,29,18,11,0,0,Michael Ward (84454920) [M],Cancelled Outside Policy Rules - Session Lost,michaelward1@bellsouth.net
1163,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,90.0 %,20,29,18,11,0,0,Patrick Whitlock (75524489) [M],Completed Booking,pwhitloc@gmail.com
1164,59,98.7 %,48.0 %,"1,180","1,165",566,580,0,1,Iron Tribe - Franklin (11043),...,90.0 %,20,29,18,11,0,0,Matt Wood (75524649) [M],Cancelled Within Policy Rules - No session cre...,matthew.d.wood85@gmail.com

In [18]:
pd.unique(week_att_df['ClassName'])

array(['Power (52741)', 'PRIME (57332)', 'Push (52476)'], dtype=object)